baseurl = "/"
languageCode = "en-us"
title = "Arindam Dawn"
enableRobotsTXT = true
googleAnalytics = "UA-143116561-1"
disqusShortname = "arindamdawn-com"

[taxonomies]
  topic = "topics"
 

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


[params.adsense]
client = "ca-pub-1035784285560337"
inArticleSlot = "5008648556"